package io.github.thatsfguy.meshcore.android.ui.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import io.github.thatsfguy.meshcore.android.ui.MeshCoreViewModel
import io.github.thatsfguy.meshcore.protocol.IdentityKey
import io.github.thatsfguy.meshcore.protocol.IdentityKeygen
import io.github.thatsfguy.meshcore.protocol.PathHashMode
import kotlinx.coroutines.launch

/**
 * A repeater's identity key (PARITY.md §6 — the row it calls the
 * highest-consequence screen in the app).
 *
 * Three deliberate refusals shape this:
 *
 *  1. **The key is never shown unasked.** Reading it puts it back on
 *     the air; that is a decision with its own confirmation, not a side
 *     effect of opening a settings tab.
 *  2. **It is never stored.** The app will not offer to remember
 *     another node's private key. Repeater *passwords* go in the
 *     Keystore because the user has to type them constantly; an
 *     identity key is typed once and belongs in whatever the user uses
 *     for backups.
 *  3. **Changing it takes a typed confirmation**, after the
 *     consequences are listed, because nothing about the result is
 *     reversible or even visible — the node simply becomes a stranger
 *     to everyone who knew it.
 *
 * The generator is the reason most people arrive here: two repeaters
 * whose public keys start with the same bytes are the same node as far
 * as a routed path is concerned, and the only fix is for one of them to
 * take a new identity. So it does not hand out a random key — it hands
 * out one whose leading bytes nobody else on this mesh answers to, at
 * the width this node is configured for. See [IdentityKeygen].
 */
@Composable
fun RepeaterIdentityPanel(vm: MeshCoreViewModel, keyHex: String, isAdmin: Boolean) {
    if (!isAdmin) {
        HintText("Log in as admin to manage this node's identity key.")
        return
    }
    val scope = rememberCoroutineScope()
    var revealed by remember(keyHex) { mutableStateOf<String?>(null) }
    var revealConfirm by remember { mutableStateOf(false) }
    var newKey by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<IdentityKeygen.Outcome?>(null) }
    var changeConfirm by remember { mutableStateOf(false) }
    var busy by remember { mutableStateOf(false) }
    var busyLabel by remember { mutableStateOf("Talking to the node…") }
    var note by remember { mutableStateOf<String?>(null) }
    // The width the node names itself by on air. Asked of the node
    // rather than assumed: it is mesh truth, this phone's radio is only
    // one member of the mesh, and a key generated against the wrong
    // width is exactly as useless as a random one.
    var widthBytes by remember(keyHex) { mutableStateOf<Int?>(null) }
    LaunchedEffect(keyHex) { widthBytes = vm.repeaterPathHashWidth(keyHex) }

    Text("Identity key", style = MaterialTheme.typography.titleSmall)
    HintText(
        "This node's Ed25519 private key. The key IS the node: everything anyone knows " +
            "about this repeater's identity is derived from it, including the leading " +
            "bytes every other node routes by.",
    )
    widthBytes?.let {
        HintText(
            "This node is named on air by the first ${PathHashMode.describeBytes(it)} of " +
                "its public key. Two repeaters sharing those bytes are one node as far as " +
                "a stored route is concerned.",
        )
    }

    ButtonFlowRow {
        TextButton(enabled = !busy, onClick = { revealConfirm = true }) { Text("Read key…") }
        TextButton(
            enabled = !busy && widthBytes != null,
            onClick = {
                val width = widthBytes
                if (width != null) {
                    busy = true
                    busyLabel = "Searching for an identity nobody else answers to…"
                    note = null
                    generated = null
                    scope.launch {
                        val outcome = vm.generateIdentityKey(width)
                        generated = outcome
                        // A failed search leaves whatever was typed
                        // alone — it is the user's key, and losing it to
                        // a button that found nothing would be its own
                        // defect.
                        if (outcome is IdentityKeygen.Outcome.Generated) {
                            newKey = outcome.candidate.privateKeyHex
                        }
                        busy = false
                    }
                }
            },
        ) { Text("Generate a new one") }
    }
    if (busy) SectionSpinner(busyLabel)
    note?.let { HintText(it) }

    revealed?.let { key ->
        Spacer(Modifier.height(8.dp))
        Text(
            key,
            style = MaterialTheme.typography.bodySmall,
            fontFamily = FontFamily.Monospace,
            color = MaterialTheme.colorScheme.error,
        )
        HintText(
            "Write this somewhere safe. It is not stored by this app, and there is no " +
                "way to recover it from the mesh if the node is lost.",
        )
        ButtonFlowRow {
            TextButton(onClick = { revealed = null }) { Text("Hide") }
        }
    }

    generated?.let { outcome ->
        Spacer(Modifier.height(8.dp))
        GeneratedKeySummary(outcome)
    }

    Spacer(Modifier.height(16.dp))
    Text("Replace the key", style = MaterialTheme.typography.titleSmall)
    OutlinedTextField(
        value = newKey,
        onValueChange = { newKey = it; generated = null },
        label = { Text("New private key (128 hex characters)") },
        singleLine = true,
        isError = newKey.isNotBlank() && !IdentityKey.isValidHex(newKey),
        modifier = Modifier.fillMaxWidth(),
    )
    if (newKey.isBlank()) {
        HintText(
            "A node stores 64 bytes — 128 hex characters. A 64-character Ed25519 seed is " +
                "accepted too and expanded here before it is sent.",
        )
    } else {
        when {
            !IdentityKey.isValidHex(newKey) -> HintText(
                "A key is 128 hex characters (64 bytes), or the 64-character seed it came " +
                    "from. Nothing in between is a key.",
            )
            IdentityKey.isDegenerate(newKey) -> Text(
                "That key is all one repeated byte. It is structurally valid and " +
                    "cryptographically worthless — anyone can reproduce it.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.error,
            )
            // A seed can be previewed; the 64-byte form cannot, because
            // deriving its public key needs a scalar multiplication
            // neither platform's Ed25519 exposes (IdentityKey docs).
            IdentityKey.canonicalSeedHex(newKey) != null ->
                vm.publicKeyFor(newKey)?.let { pub ->
                    if (!IdentityKey.isAcceptablePublicKey(pub)) {
                        Text(
                            "The node will refuse that key: its public key starts with " +
                                "${pub.take(2)}, and MeshCore rejects 00 and ff outright.",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.error,
                        )
                    } else {
                        HintText("This node would become $pub")
                        // The same rule the generator applies, applied to
                        // a key somebody typed. A hand-picked key is
                        // exactly as capable of landing on a neighbour's
                        // prefix as a random one.
                        val clash = widthBytes
                            ?.let { vm.nodesSharingPrefix(pub, it) }
                            .orEmpty()
                        if (clash.isNotEmpty()) {
                            Text(
                                "Those leading bytes are already in use by " +
                                    clash.joinToString(", ") + ". A route cannot tell " +
                                    "this node apart from that.",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.error,
                            )
                        }
                    }
                }
            generated == null -> HintText(
                "This node will report its new public key when it applies the change.",
            )
        }
    }
    ButtonFlowRow {
        TextButton(
            enabled = !busy && IdentityKey.isValidHex(newKey) && !IdentityKey.isDegenerate(newKey),
            onClick = { changeConfirm = true },
        ) { Text("Replace identity key…", color = MaterialTheme.colorScheme.error) }
    }

    if (revealConfirm) {
        AlertDialog(
            onDismissRequest = { revealConfirm = false },
            title = { Text("Read the identity key?") },
            text = {
                Column {
                    Text(IdentityKey.REVEAL_CAVEAT, style = MaterialTheme.typography.bodySmall)
                    Spacer(Modifier.height(8.dp))
                    Text(
                        IdentityKey.READS_ARE_SERIAL_ONLY,
                        style = MaterialTheme.typography.bodySmall,
                    )
                }
            },
            confirmButton = {
                TextButton(onClick = {
                    revealConfirm = false
                    busy = true
                    busyLabel = "Talking to the node…"
                    note = null
                    scope.launch {
                        val reply = vm.readIdentityKey(keyHex)
                        revealed = reply
                        if (reply == null) {
                            note = "No key came back. A node only answers this over USB " +
                                "serial, so over the mesh this is the expected answer."
                        }
                        busy = false
                    }
                }) { Text("Read it", color = MaterialTheme.colorScheme.error) }
            },
            dismissButton = {
                TextButton(onClick = { revealConfirm = false }) { Text("Cancel") }
            },
        )
    }

    if (changeConfirm) {
        ReplaceKeyDialog(
            onDismiss = { changeConfirm = false },
            onConfirm = {
                changeConfirm = false
                busy = true
                busyLabel = "Talking to the node…"
                note = null
                scope.launch {
                    note = vm.replaceIdentityKey(keyHex, newKey)
                    newKey = ""
                    generated = null
                    busy = false
                }
            },
        )
    }
}

/**
 * What the search actually found — stated in the terms that make it
 * worth doing, which are the leading bytes and the width they are
 * judged at, not the key.
 */
@Composable
private fun GeneratedKeySummary(outcome: IdentityKeygen.Outcome) {
    when (outcome) {
        is IdentityKeygen.Outcome.Generated -> {
            val prefix = outcome.candidate.prefixHex(outcome.widthBytes)
            Text(
                "This node would become ${outcome.candidate.publicKeyHex}",
                style = MaterialTheme.typography.bodySmall,
                fontFamily = FontFamily.Monospace,
            )
            HintText(
                "On air it would answer to $prefix — " +
                    PathHashMode.describeBytes(outcome.widthBytes) +
                    ", which is what this node is set to. No node this phone knows about " +
                    "uses those bytes.",
            )
            if (!outcome.clearOfFirstByte) {
                HintText(
                    "Its first byte is shared with a node already on the mesh — the " +
                        "search could not find a free one. That is the byte direct " +
                        "packets are addressed by, so those packets reach both nodes and " +
                        "are discarded by the wrong one. A nuisance, not a routing fault: " +
                        "the bytes above are still this node's alone.",
                )
            }
            HintText(
                "Write down the 64-character seed before you apply this — it is the short " +
                    "form of the same key: ${outcome.candidate.seedHex}",
            )
        }
        is IdentityKeygen.Outcome.Exhausted -> Text(
            "No free identity at " + PathHashMode.describeBytes(outcome.widthBytes) +
                ": ${outcome.takenPrefixes} of ${outcome.totalPrefixes} possible prefixes " +
                "are already in use by nodes this phone knows about. A wider path hash is " +
                "the fix, and every node on the mesh has to agree on it.",
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.error,
        )
    }
}

@Composable
private fun ReplaceKeyDialog(onDismiss: () -> Unit, onConfirm: () -> Unit) {
    var typed by remember { mutableStateOf("") }
    val armed = typed.trim().equals(CONFIRM_WORD, ignoreCase = true)

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Replace this node's identity?") },
        text = {
            Column {
                for (line in IdentityKey.CHANGE_CONSEQUENCES) {
                    Text("• $line", style = MaterialTheme.typography.bodySmall)
                    Spacer(Modifier.height(4.dp))
                }
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    value = typed,
                    onValueChange = { typed = it },
                    label = { Text("Type $CONFIRM_WORD to confirm") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth(),
                )
            }
        },
        confirmButton = {
            TextButton(onClick = onConfirm, enabled = armed) {
                Text("Replace", color = MaterialTheme.colorScheme.error)
            }
        },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancel") } },
    )
}

private const val CONFIRM_WORD = "REPLACE"
