package io.github.thatsfguy.meshcore.android.ui.screens

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Checkbox
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import io.github.thatsfguy.meshcore.android.ui.MeshCoreViewModel
import io.github.thatsfguy.meshcore.presentation.RekeyFlow
import io.github.thatsfguy.meshcore.protocol.IdentityKey
import io.github.thatsfguy.meshcore.protocol.IdentityKeygen
import io.github.thatsfguy.meshcore.protocol.PathHashMode
import kotlinx.coroutines.launch

/**
 * A repeater's identity key (PARITY.md §6 — the row it calls the
 * highest-consequence screen in the app).
 *
 * Three deliberate refusals shape this:
 *
 *  1. **The key is never shown unasked.** Reading it puts it back on
 *     the air; that is a decision with its own confirmation, not a side
 *     effect of opening a settings tab.
 *  2. **It is never stored.** The app will not offer to remember
 *     another node's private key. Repeater *passwords* go in the
 *     Keystore because the user has to type them constantly; an
 *     identity key is typed once and belongs in whatever the user uses
 *     for backups.
 *  3. **Changing it takes a typed confirmation**, after the
 *     consequences are listed, because nothing about the result is
 *     reversible or even visible — the node simply becomes a stranger
 *     to everyone who knew it.
 *
 * The generator is the reason most people arrive here: two repeaters
 * whose public keys start with the same bytes are the same node as far
 * as a routed path is concerned, and the only fix is for one of them to
 * take a new identity. So it does not hand out a random key — it hands
 * out one whose leading bytes nobody else on this mesh answers to, at
 * the width this node is configured for. See [IdentityKeygen].
 */
@Composable
fun RepeaterIdentityPanel(vm: MeshCoreViewModel, keyHex: String, isAdmin: Boolean) {
    if (!isAdmin) {
        HintText("Log in as admin to manage this node's identity key.")
        return
    }
    val scope = rememberCoroutineScope()
    var revealed by remember(keyHex) { mutableStateOf<String?>(null) }
    var revealConfirm by remember { mutableStateOf(false) }
    var newKey by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf<IdentityKeygen.Outcome?>(null) }
    var changeConfirm by remember { mutableStateOf(false) }
    var busy by remember { mutableStateOf(false) }
    var busyLabel by remember { mutableStateOf("Talking to the node…") }
    var note by remember { mutableStateOf<String?>(null) }
    // The rekey report is several lines and each one is a separate
    // claim; joining them into a sentence is how a report starts
    // saying more than it knows.
    var report by remember { mutableStateOf<List<String>>(emptyList()) }
    // The width the node names itself by on air. Asked of the node
    // rather than assumed: it is mesh truth, this phone's radio is only
    // one member of the mesh, and a key generated against the wrong
    // width is exactly as useless as a random one.
    var widthBytes by remember(keyHex) { mutableStateOf<Int?>(null) }
    LaunchedEffect(keyHex) { widthBytes = vm.repeaterPathHashWidth(keyHex) }

    Text("Identity key", style = MaterialTheme.typography.titleSmall)
    HintText("This node's Ed25519 private key. The key IS the node.")
    widthBytes?.let { bytes ->
        ExpandableHint("On air it is named by its first ${PathHashMode.describeBytes(bytes)}.") {
            HintText(
                "A routed path carries only those leading bytes, so two repeaters that " +
                    "share them are one node as far as a stored route is concerned.",
            )
            HintText(
                "That is what a new key is chosen to avoid, and it is the node's own " +
                    "setting — every node on the mesh has to agree on it.",
            )
        }
    }

    ButtonFlowRow {
        TextButton(enabled = !busy, onClick = { revealConfirm = true }) { Text("Read key…") }
        TextButton(
            enabled = !busy && widthBytes != null,
            onClick = {
                val width = widthBytes
                if (width != null) {
                    busy = true
                    busyLabel = "Searching for an identity nobody else answers to…"
                    note = null
                    generated = null
                    scope.launch {
                        val outcome = vm.generateIdentityKey(width)
                        generated = outcome
                        if (outcome != null) {
                            newKey = outcome.candidate.privateKeyHex
                        } else {
                            // Only ever a platform failure — the search
                            // itself always returns something, even if
                            // it had to settle for a clash. Leave what
                            // was typed alone; it is the user's key.
                            note = "This device could not generate a key pair."
                        }
                        busy = false
                    }
                }
            },
        ) { Text("Generate a new one") }
    }
    if (busy) SectionSpinner(busyLabel)
    note?.let { HintText(it) }
    if (report.isNotEmpty()) {
        Spacer(Modifier.height(8.dp))
        for (line in report) {
            Text("• $line", style = MaterialTheme.typography.bodySmall)
            Spacer(Modifier.height(4.dp))
        }
    }

    revealed?.let { key ->
        Spacer(Modifier.height(8.dp))
        Text(
            key,
            style = MaterialTheme.typography.bodySmall,
            fontFamily = FontFamily.Monospace,
            color = MaterialTheme.colorScheme.error,
        )
        HintText(
            "Write this somewhere safe. It is not stored by this app, and there is no " +
                "way to recover it from the mesh if the node is lost.",
        )
        ButtonFlowRow {
            TextButton(onClick = { revealed = null }) { Text("Hide") }
        }
    }

    generated?.let { outcome ->
        Spacer(Modifier.height(8.dp))
        GeneratedKeySummary(outcome)
    }

    Spacer(Modifier.height(16.dp))
    Text("Replace the key", style = MaterialTheme.typography.titleSmall)
    OutlinedTextField(
        value = newKey,
        onValueChange = { newKey = it; generated = null },
        label = { Text("New private key (128 hex characters)") },
        singleLine = true,
        isError = newKey.isNotBlank() && !IdentityKey.isValidHex(newKey),
        modifier = Modifier.fillMaxWidth(),
    )
    if (newKey.isBlank()) {
        HintText(
            "A node stores 64 bytes — 128 hex characters. A 64-character Ed25519 seed is " +
                "accepted too and expanded here before it is sent.",
        )
    } else {
        when {
            !IdentityKey.isValidHex(newKey) -> HintText(
                "A key is 128 hex characters (64 bytes), or the 64-character seed it came " +
                    "from. Nothing in between is a key.",
            )
            IdentityKey.isDegenerate(newKey) -> Text(
                "That key is all one repeated byte. It is structurally valid and " +
                    "cryptographically worthless — anyone can reproduce it.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.error,
            )
            // A seed can be previewed; the 64-byte form cannot, because
            // deriving its public key needs a scalar multiplication
            // neither platform's Ed25519 exposes (IdentityKey docs).
            IdentityKey.canonicalSeedHex(newKey) != null ->
                vm.publicKeyFor(newKey)?.let { pub ->
                    if (!IdentityKey.isAcceptablePublicKey(pub)) {
                        Text(
                            "The node will refuse that key: its public key starts with " +
                                "${pub.take(2)}, and MeshCore rejects 00 and ff outright.",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.error,
                        )
                    } else {
                        HintText("This node would become $pub")
                        // The same rule the generator applies, applied to
                        // a key somebody typed. A hand-picked key is
                        // exactly as capable of landing on a neighbour's
                        // prefix as a random one.
                        val clash = widthBytes
                            ?.let { vm.nodesSharingPrefix(pub, it) }
                            .orEmpty()
                        if (clash.isNotEmpty()) {
                            Text(
                                "Those leading bytes are already in use by " +
                                    clash.joinToString(", ") + ". A route cannot tell " +
                                    "this node apart from that.",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.error,
                            )
                        }
                    }
                }
            generated == null -> HintText(
                "This node will report its new public key when it applies the change.",
            )
        }
    }
    ButtonFlowRow {
        TextButton(
            enabled = !busy && IdentityKey.isValidHex(newKey) && !IdentityKey.isDegenerate(newKey),
            onClick = { changeConfirm = true },
        ) { Text("Replace identity key…", color = MaterialTheme.colorScheme.error) }
    }

    if (revealConfirm) {
        AlertDialog(
            onDismissRequest = { revealConfirm = false },
            title = { Text("Read the identity key?") },
            text = {
                Column {
                    Text(IdentityKey.REVEAL_CAVEAT, style = MaterialTheme.typography.bodySmall)
                    Spacer(Modifier.height(8.dp))
                    Text(
                        IdentityKey.READS_ARE_SERIAL_ONLY,
                        style = MaterialTheme.typography.bodySmall,
                    )
                }
            },
            confirmButton = {
                TextButton(onClick = {
                    revealConfirm = false
                    busy = true
                    busyLabel = "Talking to the node…"
                    note = null
                    scope.launch {
                        val reply = vm.readIdentityKey(keyHex)
                        revealed = reply
                        if (reply == null) {
                            note = "No key came back. A node only answers this over USB " +
                                "serial, so over the mesh this is the expected answer."
                        }
                        busy = false
                    }
                }) { Text("Read it", color = MaterialTheme.colorScheme.error) }
            },
            dismissButton = {
                TextButton(onClick = { revealConfirm = false }) { Text("Cancel") }
            },
        )
    }

    if (changeConfirm) {
        ReplaceKeyDialog(
            onDismiss = { changeConfirm = false },
            onConfirm = { reboot ->
                changeConfirm = false
                busy = true
                busyLabel = "Talking to the node…"
                note = null
                report = emptyList()
                val applying = newKey
                scope.launch {
                    // Cleared before the sequence, not after: it runs for
                    // half a minute when a reboot is asked for, and a key
                    // still sitting in the box behind a spinner invites a
                    // second press of a button that cannot be undone.
                    newKey = ""
                    generated = null
                    report = RekeyFlow.describe(
                        vm.replaceIdentityKey(keyHex, applying, reboot) { step ->
                            busyLabel = step
                        },
                    )
                    busy = false
                }
            },
        )
    }
}

/**
 * What the search actually found — stated in the terms that make it
 * worth doing, which are the leading bytes and the width they are
 * judged at, not the key.
 *
 * A clash is never left implied. The search picks the least harmful one
 * available when there is no clean key, and which node it picked is the
 * entire difference between a harmless coincidence and a broken route —
 * so it is named, with how far away it is.
 */
@Composable
private fun GeneratedKeySummary(outcome: IdentityKeygen.Outcome) {
    val prefix = outcome.candidate.prefixHex(outcome.widthBytes)
    val width = PathHashMode.describeBytes(outcome.widthBytes)
    Text(
        "This node would become ${outcome.candidate.publicKeyHex}",
        style = MaterialTheme.typography.bodySmall,
        fontFamily = FontFamily.Monospace,
    )
    val clash = outcome.clash
    when {
        clash == null -> HintText(
            "On air it would answer to $prefix — $width, which is what this node is set " +
                "to. No node this phone knows about uses those bytes, at that width or " +
                "as a destination hash.",
        )

        clash.level == IdentityKeygen.ClashLevel.DESTINATION -> {
            HintText(
                "On air it would answer to $prefix — $width, which is what this node is " +
                    "set to. No node this phone knows about uses those bytes.",
            )
            ExpandableHint("Its first byte is shared with ${clash.with.label}.") {
                HintText(
                    "That is the byte direct packets are addressed by, so they reach " +
                        "both nodes and the wrong one discards them.",
                )
                HintText(
                    "A nuisance, not a routing fault — and no first byte was left free, " +
                        "so the search took the most distant node to share one with.",
                )
            }
        }

        else -> {
            Text(
                "No free identity left at $width. This key shares $prefix with " +
                    "${clash.with.label} — a real routing clash.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.error,
            )
            ExpandableHint("It is the best available, and still a clash.") {
                HintText(
                    "${outcome.takenPrefixes} of the " +
                        "${IdentityKeygen.totalPrefixes(outcome.widthBytes)} possible " +
                        "names at this width are already in use.",
                )
                HintText(
                    "The search took the furthest node it could find to collide with. " +
                        "Widening the path hash is the actual fix.",
                )
            }
        }
    }
    HintText(
        "Write down the 64-character seed before you apply this — it is the short " +
            "form of the same key: ${outcome.candidate.seedHex}",
    )
}

/**
 * The last stop before a node changes its name for ever.
 *
 * The restart checkbox is on by default, and that is the honest default
 * rather than the convenient one: a stored key does nothing at all until
 * the node restarts (`CommonCLI.cpp:518` — "OK, reboot to apply!"), so
 * leaving it off produces the state that confuses everyone — a node
 * reporting one identity while still answering to another. Unticking it
 * is for when the restart has to happen at a chosen moment.
 *
 * Both firmware facts are stated here rather than in the outcome,
 * because they change what the user should expect BEFORE they commit:
 * nothing acknowledges a reboot, and a rebooted node does not announce
 * itself anywhere the phone can hear.
 */
@Composable
private fun ReplaceKeyDialog(onDismiss: () -> Unit, onConfirm: (Boolean) -> Unit) {
    var typed by remember { mutableStateOf("") }
    var reboot by remember { mutableStateOf(true) }
    val armed = typed.trim().equals(CONFIRM_WORD, ignoreCase = true)

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Replace this node's identity?") },
        text = {
            Column {
                for (line in IdentityKey.CHANGE_CONSEQUENCES) {
                    Text("• $line", style = MaterialTheme.typography.bodySmall)
                    Spacer(Modifier.height(4.dp))
                }
                Spacer(Modifier.height(8.dp))
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier.fillMaxWidth().clickable { reboot = !reboot },
                ) {
                    Checkbox(checked = reboot, onCheckedChange = { reboot = it })
                    Text(
                        "Restart the node now to apply it",
                        style = MaterialTheme.typography.bodySmall,
                    )
                }
                HintText(IdentityKey.REBOOT_HAS_NO_ANSWER)
                HintText(IdentityKey.NEW_IDENTITY_IS_NOT_ANNOUNCED)
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    value = typed,
                    onValueChange = { typed = it },
                    label = { Text("Type $CONFIRM_WORD to confirm") },
                    singleLine = true,
                    keyboardOptions = VERBATIM_KEYBOARD,
                    modifier = Modifier.fillMaxWidth(),
                )
            }
        },
        confirmButton = {
            TextButton(onClick = { onConfirm(reboot) }, enabled = armed) {
                Text(
                    if (reboot) "Replace and restart" else "Replace",
                    color = MaterialTheme.colorScheme.error,
                )
            }
        },
        dismissButton = { TextButton(onClick = onDismiss) { Text("Cancel") } },
    )
}

private const val CONFIRM_WORD = "REPLACE"
